### ISSUE TITLE
Invalid format string

### ISSUE THREAD

**Issue by my1e5** [noprobelm/tempy#24] opened 2023-01-26 14:02 UTC
Installed `v1.0.9` via `pip install git+https://github.com/noprobelm/tempy`. Getting an invalid format string error: 
```bash
$ tempy new york city
Traceback (most recent call last):
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\Scripts\tempy.exe\__main__.py", line 7, in <module>
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\tempy\__main__.py", line 8, in main
    renderable = Report(config)
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\tempy\weather.py", line 69, in __init__
    self.data = Data(config["location"], config["api_key"])
  File "C:\Users\User\AppData\Local\Programs\Python\Python310\lib\site-packages\tempy\data.py", line 34, in __init__
    ).strftime("%A, %B %-d | %H:%M"),
ValueError: Invalid format string
```
Python 3.10 and Windows 10

**Comment by my1e5** [comment] 2023-01-26 14:57
I think it's because `https://noprobelm.dev/` is not working for me.

**Comment by noprobelm** [comment] 2023-01-26 15:05
The problem isn't the domain, I just tested it.

There's definitely an issue to sort out here for Windows users. Shouldn't be difficult at all. I'll take a look here shortly and hopefully have it resolved by this afternoon. 

Thank you for identifying this problem.

**Comment by my1e5** [comment] 2023-01-26 15:26
Ok great, thanks! 

Out of interest - should I be able to load `https://noprobelm.dev/` in my web browser? When I try I get `ERR_CONNECTION_TIMED_OUT`.

**Comment by noprobelm** [comment] 2023-01-26 15:42
Nope, because I'm not serving an actual web page. I'm just forwarding each user's request on to weatherapi.com.

However, you can test your ability to communicate with `noprobelm.dev` using the `requests` module.

```
import requests
requests.get("http://noprobelm.dev")
```

Should produce
`<Response 200>`

**Closed** 2023-01-26 19:48 UTC

**Comment by noprobelm** [comment] 2023-01-26 19:50
@my1e5 You should be good to go. I don't have a very well configured Windows machine, so let me know if you have any issues with the changes and I will address them.

Try reinstalling `tempy` and let me know if everything works for you.

**Comment by my1e5** [comment] 2023-01-30 11:47
Everything working for me - thanks!
